-- ═══════════════════════════════════════════════════════════════════════════
-- Plan Único de Cuentas (PUC) — Decreto 2650 de 1993, Colombia
-- Cuentas principales (clase, grupo, cuenta, subcuenta) más utilizadas.
-- INSERT IGNORE para que sea idempotente: si una cuenta ya existe, se omite.
-- ═══════════════════════════════════════════════════════════════════════════

-- ───────────────── CLASE 1 — ACTIVO ─────────────────
INSERT IGNORE INTO cuentas_contables (codigo, nombre, tipo, naturaleza, nivel, padre_id, es_movimiento, estado) VALUES
('1',      'ACTIVO',                       'ACTIVO', 'DEBITO', 1, NULL, b'0', 'ACTIVO'),
('11',     'DISPONIBLE',                   'ACTIVO', 'DEBITO', 2, NULL, b'0', 'ACTIVO'),
('1105',   'CAJA',                         'ACTIVO', 'DEBITO', 3, NULL, b'0', 'ACTIVO'),
('110505', 'Caja general',                 'ACTIVO', 'DEBITO', 4, NULL, b'1', 'ACTIVO'),
('110510', 'Cajas menores',                'ACTIVO', 'DEBITO', 4, NULL, b'1', 'ACTIVO'),
('110515', 'Moneda extranjera',            'ACTIVO', 'DEBITO', 4, NULL, b'1', 'ACTIVO'),
('1110',   'BANCOS',                       'ACTIVO', 'DEBITO', 3, NULL, b'0', 'ACTIVO'),
('111005', 'Moneda nacional',              'ACTIVO', 'DEBITO', 4, NULL, b'1', 'ACTIVO'),
('111010', 'Moneda extranjera',            'ACTIVO', 'DEBITO', 4, NULL, b'1', 'ACTIVO'),
('1115',   'REMESAS EN TRÁNSITO',          'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1120',   'CUENTAS DE AHORRO',            'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1125',   'FONDOS',                       'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),

('12',     'INVERSIONES',                  'ACTIVO', 'DEBITO', 2, NULL, b'0', 'ACTIVO'),
('1205',   'Acciones',                     'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1210',   'Cuotas o partes de interés social','ACTIVO','DEBITO',3,NULL, b'1', 'ACTIVO'),
('1215',   'Bonos',                        'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1220',   'Cédulas',                      'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1225',   'Certificados',                 'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1230',   'Papeles comerciales',          'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1235',   'Títulos',                      'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1295',   'Otras inversiones',            'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),

('13',     'DEUDORES',                     'ACTIVO', 'DEBITO', 2, NULL, b'0', 'ACTIVO'),
('1305',   'CLIENTES',                     'ACTIVO', 'DEBITO', 3, NULL, b'0', 'ACTIVO'),
('130505', 'Clientes nacionales',          'ACTIVO', 'DEBITO', 4, NULL, b'1', 'ACTIVO'),
('130510', 'Clientes del exterior',        'ACTIVO', 'DEBITO', 4, NULL, b'1', 'ACTIVO'),
('130515', 'Deudores del sistema',         'ACTIVO', 'DEBITO', 4, NULL, b'1', 'ACTIVO'),
('1310',   'CUENTAS CORRIENTES COMERCIALES','ACTIVO','DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1315',   'CUENTAS POR COBRAR A CASA MATRIZ','ACTIVO','DEBITO',3,NULL, b'1', 'ACTIVO'),
('1320',   'CUENTAS POR COBRAR A VINCULADOS','ACTIVO','DEBITO',3,NULL, b'1', 'ACTIVO'),
('1323',   'CUENTAS POR COBRAR A DIRECTORES','ACTIVO','DEBITO',3,NULL, b'1', 'ACTIVO'),
('1325',   'CUENTAS POR COBRAR A SOCIOS Y ACCIONISTAS','ACTIVO','DEBITO',3,NULL, b'1', 'ACTIVO'),
('1330',   'ANTICIPOS Y AVANCES',          'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1332',   'CUENTAS DE OPERACIÓN CONJUNTA','ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1335',   'DEPÓSITOS',                    'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1340',   'PROMESAS DE COMPRAVENTA',      'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1345',   'INGRESOS POR COBRAR',          'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1350',   'RETENCIÓN SOBRE CONTRATOS',    'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1355',   'ANTICIPO DE IMPUESTOS Y CONTRIBUCIONES','ACTIVO','DEBITO',3,NULL,b'0','ACTIVO'),
('135505', 'Anticipo de impuestos de renta',  'ACTIVO', 'DEBITO', 4, NULL, b'1', 'ACTIVO'),
('135510', 'Anticipo de impuestos de industria y comercio','ACTIVO','DEBITO',4,NULL,b'1','ACTIVO'),
('135515', 'Retención en la fuente',       'ACTIVO', 'DEBITO', 4, NULL, b'1', 'ACTIVO'),
('135517', 'Impuesto a las ventas retenido','ACTIVO', 'DEBITO', 4, NULL, b'1', 'ACTIVO'),
('135518', 'Impuesto de industria y comercio retenido','ACTIVO','DEBITO',4,NULL,b'1','ACTIVO'),
('135525', 'Sobrantes en liquidación',     'ACTIVO', 'DEBITO', 4, NULL, b'1', 'ACTIVO'),
('135530', 'Contribuciones',               'ACTIVO', 'DEBITO', 4, NULL, b'1', 'ACTIVO'),
('1360',   'RECLAMACIONES',                'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1365',   'CUENTAS POR COBRAR A TRABAJADORES','ACTIVO','DEBITO',3,NULL, b'1', 'ACTIVO'),
('1370',   'PRÉSTAMOS A PARTICULARES',     'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1380',   'DEUDORES VARIOS',              'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1385',   'DERECHOS DE RECOMPRA',         'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1390',   'DEUDAS DE DIFÍCIL COBRO',      'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1399',   'PROVISIONES',                  'ACTIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),

('14',     'INVENTARIOS',                  'ACTIVO', 'DEBITO', 2, NULL, b'0', 'ACTIVO'),
('1405',   'MATERIAS PRIMAS',              'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1410',   'PRODUCTOS EN PROCESO',         'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1415',   'OBRAS DE CONSTRUCCIÓN EN CURSO','ACTIVO','DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1417',   'OBRAS DE URBANISMO',           'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1420',   'CONTRATOS EN EJECUCIÓN',       'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1425',   'CULTIVOS EN DESARROLLO',       'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1430',   'PRODUCTOS TERMINADOS',         'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1435',   'MERCANCÍAS NO FABRICADAS POR LA EMPRESA','ACTIVO','DEBITO',3,NULL,b'1','ACTIVO'),
('1440',   'BIENES RAÍCES PARA LA VENTA',  'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1445',   'SEMOVIENTES',                  'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1450',   'TERRENOS',                     'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1455',   'MATERIALES, REPUESTOS Y ACCESORIOS','ACTIVO','DEBITO',3,NULL,b'1','ACTIVO'),
('1460',   'ENVASES Y EMPAQUES',           'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1465',   'INVENTARIOS EN TRÁNSITO',      'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1499',   'PROVISIONES',                  'ACTIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),

('15',     'PROPIEDADES, PLANTA Y EQUIPO', 'ACTIVO', 'DEBITO', 2, NULL, b'0', 'ACTIVO'),
('1504',   'TERRENOS',                     'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1508',   'MATERIALES PROYECTOS PETROLEROS','ACTIVO','DEBITO',3,NULL, b'1', 'ACTIVO'),
('1512',   'CONSTRUCCIONES EN CURSO',      'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1516',   'CONSTRUCCIONES Y EDIFICACIONES','ACTIVO','DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1520',   'MAQUINARIA Y EQUIPO',          'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1524',   'EQUIPO DE OFICINA',            'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1528',   'EQUIPO DE COMPUTACIÓN Y COMUNICACIÓN','ACTIVO','DEBITO',3,NULL,b'1','ACTIVO'),
('1532',   'EQUIPO MÉDICO-CIENTÍFICO',     'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1540',   'FLOTA Y EQUIPO DE TRANSPORTE', 'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1544',   'FLOTA Y EQUIPO FLUVIAL Y/O MARÍTIMO','ACTIVO','DEBITO',3,NULL,b'1','ACTIVO'),
('1548',   'FLOTA Y EQUIPO AÉREO',         'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1552',   'FLOTA Y EQUIPO FÉRREO',        'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1592',   'DEPRECIACIÓN ACUMULADA',       'ACTIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('1596',   'DEPRECIACIÓN DIFERIDA',        'ACTIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),

('16',     'INTANGIBLES',                  'ACTIVO', 'DEBITO', 2, NULL, b'0', 'ACTIVO'),
('1605',   'CRÉDITO MERCANTIL',            'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1610',   'MARCAS',                       'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1615',   'PATENTES',                     'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1620',   'CONCESIONES Y FRANQUICIAS',    'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1625',   'DERECHOS',                     'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1630',   'KNOW HOW',                     'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1635',   'LICENCIAS',                    'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1698',   'DEPRECIACIÓN Y/O AMORTIZACIÓN ACUMULADA','ACTIVO','CREDITO',3,NULL,b'1','ACTIVO'),
('1699',   'PROVISIONES',                  'ACTIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),

('17',     'DIFERIDOS',                    'ACTIVO', 'DEBITO', 2, NULL, b'0', 'ACTIVO'),
('1705',   'GASTOS PAGADOS POR ANTICIPADO','ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1710',   'CARGOS DIFERIDOS',             'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1715',   'COSTOS DE EXPLORACIÓN POR AMORTIZAR','ACTIVO','DEBITO',3,NULL,b'1','ACTIVO'),
('1720',   'COSTOS DE EXPLOTACIÓN Y DESARROLLO','ACTIVO','DEBITO',3,NULL,b'1','ACTIVO'),
('1730',   'CARGOS POR CORRECCIÓN MONETARIA DIFERIDA','ACTIVO','DEBITO',3,NULL,b'1','ACTIVO'),

('18',     'OTROS ACTIVOS',                'ACTIVO', 'DEBITO', 2, NULL, b'0', 'ACTIVO'),
('1805',   'BIENES DE ARTE Y CULTURA',     'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1895',   'DIVERSOS',                     'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),

('19',     'VALORIZACIONES',               'ACTIVO', 'DEBITO', 2, NULL, b'0', 'ACTIVO'),
('1905',   'DE INVERSIONES',               'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1910',   'DE PROPIEDADES PLANTA Y EQUIPO','ACTIVO','DEBITO', 3, NULL, b'1', 'ACTIVO'),
('1995',   'DE OTROS ACTIVOS',             'ACTIVO', 'DEBITO', 3, NULL, b'1', 'ACTIVO');

-- ───────────────── CLASE 2 — PASIVO ─────────────────
INSERT IGNORE INTO cuentas_contables (codigo, nombre, tipo, naturaleza, nivel, padre_id, es_movimiento, estado) VALUES
('2',      'PASIVO',                       'PASIVO', 'CREDITO', 1, NULL, b'0', 'ACTIVO'),
('21',     'OBLIGACIONES FINANCIERAS',     'PASIVO', 'CREDITO', 2, NULL, b'0', 'ACTIVO'),
('2105',   'BANCOS NACIONALES',            'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2110',   'BANCOS DEL EXTERIOR',          'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2115',   'CORPORACIONES FINANCIERAS',    'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2120',   'COMPAÑÍAS DE FINANCIAMIENTO COMERCIAL','PASIVO','CREDITO',3,NULL,b'1','ACTIVO'),
('2125',   'CORPORACIONES DE AHORRO Y VIVIENDA','PASIVO','CREDITO',3,NULL,b'1','ACTIVO'),
('2130',   'ENTIDADES FINANCIERAS DEL EXTERIOR','PASIVO','CREDITO',3,NULL,b'1','ACTIVO'),
('2135',   'COMPROMISOS DE RECOMPRA',      'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2140',   'OBLIGACIONES GUBERNAMENTALES', 'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2195',   'OTRAS OBLIGACIONES',           'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),

('22',     'PROVEEDORES',                  'PASIVO', 'CREDITO', 2, NULL, b'0', 'ACTIVO'),
('2205',   'NACIONALES',                   'PASIVO', 'CREDITO', 3, NULL, b'0', 'ACTIVO'),
('220505', 'Proveedores nacionales',       'PASIVO', 'CREDITO', 4, NULL, b'1', 'ACTIVO'),
('2210',   'DEL EXTERIOR',                 'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2215',   'CUENTAS CORRIENTES COMERCIALES','PASIVO','CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2220',   'CASA MATRIZ',                  'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2225',   'COMPAÑÍAS VINCULADAS',         'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),

('23',     'CUENTAS POR PAGAR',            'PASIVO', 'CREDITO', 2, NULL, b'0', 'ACTIVO'),
('2305',   'CUENTAS CORRIENTES COMERCIALES','PASIVO','CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2310',   'A CASA MATRIZ',                'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2315',   'A COMPAÑÍAS VINCULADAS',       'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2320',   'A CONTRATISTAS',               'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2330',   'ÓRDENES DE COMPRA POR UTILIZAR','PASIVO','CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2335',   'COSTOS Y GASTOS POR PAGAR',    'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2340',   'INSTALAMENTOS POR PAGAR',      'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2345',   'ACREEDORES OFICIALES',         'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2350',   'REGALÍAS POR PAGAR',           'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2355',   'DEUDAS CON ACCIONISTAS O SOCIOS','PASIVO','CREDITO',3,NULL, b'1', 'ACTIVO'),
('2360',   'DIVIDENDOS O PARTICIPACIONES POR PAGAR','PASIVO','CREDITO',3,NULL,b'1','ACTIVO'),
('2365',   'RETENCIÓN EN LA FUENTE',       'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2367',   'IMPUESTO A LAS VENTAS RETENIDO','PASIVO','CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2368',   'IMPUESTO DE INDUSTRIA Y COMERCIO RETENIDO','PASIVO','CREDITO',3,NULL,b'1','ACTIVO'),
('2370',   'RETENCIONES Y APORTES DE NÓMINA','PASIVO','CREDITO',3,NULL, b'1', 'ACTIVO'),
('2380',   'ACREEDORES VARIOS',            'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),

('24',     'IMPUESTOS, GRAVÁMENES Y TASAS','PASIVO','CREDITO', 2, NULL, b'0', 'ACTIVO'),
('2404',   'DE RENTA Y COMPLEMENTARIOS',   'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2408',   'IMPUESTO SOBRE LAS VENTAS POR PAGAR','PASIVO','CREDITO',3,NULL,b'0','ACTIVO'),
('240801', 'IVA generado',                 'PASIVO', 'CREDITO', 4, NULL, b'1', 'ACTIVO'),
('240810', 'IVA descontable',              'PASIVO', 'DEBITO',  4, NULL, b'1', 'ACTIVO'),
('2412',   'DE INDUSTRIA Y COMERCIO',      'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2424',   'DE VEHÍCULOS',                 'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2495',   'OTROS',                        'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),

('25',     'OBLIGACIONES LABORALES',       'PASIVO', 'CREDITO', 2, NULL, b'0', 'ACTIVO'),
('2505',   'SALARIOS POR PAGAR',           'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2510',   'CESANTÍAS CONSOLIDADAS',       'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2515',   'INTERESES SOBRE CESANTÍAS',    'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2520',   'PRIMA DE SERVICIOS',           'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2525',   'VACACIONES CONSOLIDADAS',      'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2530',   'PRESTACIONES EXTRALEGALES',    'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2532',   'PENSIONES POR PAGAR',          'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),

('26',     'PASIVOS ESTIMADOS Y PROVISIONES','PASIVO','CREDITO',2, NULL, b'0', 'ACTIVO'),
('2605',   'PARA COSTOS Y GASTOS',         'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2610',   'PARA OBLIGACIONES LABORALES',  'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),

('27',     'DIFERIDOS',                    'PASIVO', 'CREDITO', 2, NULL, b'0', 'ACTIVO'),
('2705',   'INGRESOS RECIBIDOS POR ANTICIPADO','PASIVO','CREDITO',3,NULL,b'1','ACTIVO'),
('2710',   'ABONOS DIFERIDOS',             'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),

('28',     'OTROS PASIVOS',                'PASIVO', 'CREDITO', 2, NULL, b'0', 'ACTIVO'),
('2805',   'ANTICIPOS Y AVANCES RECIBIDOS','PASIVO','CREDITO',  3, NULL, b'1', 'ACTIVO'),
('2810',   'DEPÓSITOS RECIBIDOS',          'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('2815',   'INGRESOS RECIBIDOS PARA TERCEROS','PASIVO','CREDITO',3,NULL,b'1','ACTIVO'),
('2895',   'DIVERSOS',                     'PASIVO', 'CREDITO', 3, NULL, b'1', 'ACTIVO');

-- ───────────────── CLASE 3 — PATRIMONIO ─────────────────
INSERT IGNORE INTO cuentas_contables (codigo, nombre, tipo, naturaleza, nivel, padre_id, es_movimiento, estado) VALUES
('3',      'PATRIMONIO',                   'PATRIMONIO', 'CREDITO', 1, NULL, b'0', 'ACTIVO'),
('31',     'CAPITAL SOCIAL',               'PATRIMONIO', 'CREDITO', 2, NULL, b'0', 'ACTIVO'),
('3105',   'CAPITAL SUSCRITO Y PAGADO',    'PATRIMONIO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('3115',   'APORTES SOCIALES',             'PATRIMONIO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),

('32',     'SUPERÁVIT DE CAPITAL',         'PATRIMONIO', 'CREDITO', 2, NULL, b'0', 'ACTIVO'),
('3205',   'PRIMA EN COLOCACIÓN DE ACCIONES','PATRIMONIO','CREDITO',3,NULL,b'1','ACTIVO'),

('33',     'RESERVAS',                     'PATRIMONIO', 'CREDITO', 2, NULL, b'0', 'ACTIVO'),
('3305',   'RESERVAS OBLIGATORIAS',        'PATRIMONIO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('3310',   'RESERVAS ESTATUTARIAS',        'PATRIMONIO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('3315',   'RESERVAS OCASIONALES',         'PATRIMONIO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),

('34',     'REVALORIZACIÓN DEL PATRIMONIO','PATRIMONIO','CREDITO', 2, NULL, b'0', 'ACTIVO'),

('36',     'RESULTADOS DEL EJERCICIO',     'PATRIMONIO', 'CREDITO', 2, NULL, b'0', 'ACTIVO'),
('3605',   'UTILIDAD DEL EJERCICIO',       'PATRIMONIO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('3610',   'PÉRDIDA DEL EJERCICIO',        'PATRIMONIO', 'DEBITO',  3, NULL, b'1', 'ACTIVO'),

('37',     'RESULTADOS DE EJERCICIOS ANTERIORES','PATRIMONIO','CREDITO',2,NULL,b'0','ACTIVO'),
('3705',   'UTILIDADES ACUMULADAS',        'PATRIMONIO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('3710',   'PÉRDIDAS ACUMULADAS',          'PATRIMONIO', 'DEBITO',  3, NULL, b'1', 'ACTIVO');

-- ───────────────── CLASE 4 — INGRESOS ─────────────────
INSERT IGNORE INTO cuentas_contables (codigo, nombre, tipo, naturaleza, nivel, padre_id, es_movimiento, estado) VALUES
('4',      'INGRESOS',                     'INGRESO', 'CREDITO', 1, NULL, b'0', 'ACTIVO'),
('41',     'OPERACIONALES',                'INGRESO', 'CREDITO', 2, NULL, b'0', 'ACTIVO'),
('4105',   'AGRICULTURA, GANADERÍA, CAZA Y SILVICULTURA','INGRESO','CREDITO',3,NULL,b'1','ACTIVO'),
('4110',   'PESCA',                        'INGRESO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('4115',   'EXPLOTACIÓN DE MINAS Y CANTERAS','INGRESO','CREDITO',3,NULL, b'1', 'ACTIVO'),
('4120',   'INDUSTRIAS MANUFACTURERAS',    'INGRESO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('4125',   'SUMINISTRO DE ELECTRICIDAD, GAS Y AGUA','INGRESO','CREDITO',3,NULL,b'1','ACTIVO'),
('4130',   'CONSTRUCCIÓN',                 'INGRESO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('4135',   'COMERCIO AL POR MAYOR Y AL POR MENOR','INGRESO','CREDITO',3,NULL,b'0','ACTIVO'),
('413505', 'Venta de mercancías',          'INGRESO', 'CREDITO', 4, NULL, b'1', 'ACTIVO'),
('413510', 'Comercio al detal',            'INGRESO', 'CREDITO', 4, NULL, b'1', 'ACTIVO'),
('4140',   'HOTELES Y RESTAURANTES',       'INGRESO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('4145',   'TRANSPORTE, ALMACENAMIENTO Y COMUNICACIONES','INGRESO','CREDITO',3,NULL,b'1','ACTIVO'),
('4150',   'ACTIVIDAD FINANCIERA',         'INGRESO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('4155',   'ACTIVIDADES INMOBILIARIAS, EMPRESARIALES Y DE ALQUILER','INGRESO','CREDITO',3,NULL,b'1','ACTIVO'),
('4160',   'ENSEÑANZA',                    'INGRESO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('4165',   'SERVICIOS SOCIALES Y DE SALUD','INGRESO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('4170',   'OTRAS ACTIVIDADES DE SERVICIOS COMUNITARIOS, SOCIALES Y PERSONALES','INGRESO','CREDITO',3,NULL,b'1','ACTIVO'),
('4175',   'DEVOLUCIONES EN VENTAS (DB)',  'INGRESO', 'DEBITO',  3, NULL, b'1', 'ACTIVO'),

('42',     'NO OPERACIONALES',             'INGRESO', 'CREDITO', 2, NULL, b'0', 'ACTIVO'),
('4205',   'OTRAS VENTAS',                 'INGRESO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('4210',   'FINANCIEROS',                  'INGRESO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('4215',   'DIVIDENDOS Y PARTICIPACIONES', 'INGRESO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('4218',   'INGRESOS MÉTODO DE PARTICIPACIÓN','INGRESO','CREDITO',3,NULL, b'1', 'ACTIVO'),
('4220',   'ARRENDAMIENTOS',               'INGRESO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('4225',   'COMISIONES',                   'INGRESO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('4230',   'HONORARIOS',                   'INGRESO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('4235',   'SERVICIOS',                    'INGRESO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('4240',   'UTILIDAD EN VENTA DE INVERSIONES','INGRESO','CREDITO',3,NULL, b'1', 'ACTIVO'),
('4245',   'UTILIDAD EN VENTA DE PROPIEDADES PLANTA Y EQUIPO','INGRESO','CREDITO',3,NULL,b'1','ACTIVO'),
('4250',   'UTILIDAD EN VENTA DE OTROS BIENES','INGRESO','CREDITO',3,NULL,b'1','ACTIVO'),
('4255',   'RECUPERACIONES',               'INGRESO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('4260',   'INDEMNIZACIONES',              'INGRESO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),
('4265',   'PARTICIPACIONES EN CONCESIONES','INGRESO','CREDITO', 3, NULL, b'1', 'ACTIVO'),
('4275',   'DEVOLUCIONES EN OTRAS VENTAS', 'INGRESO', 'DEBITO',  3, NULL, b'1', 'ACTIVO'),
('4295',   'DIVERSOS',                     'INGRESO', 'CREDITO', 3, NULL, b'1', 'ACTIVO'),

('47',     'AJUSTES POR INFLACIÓN',        'INGRESO', 'CREDITO', 2, NULL, b'1', 'ACTIVO');

-- ───────────────── CLASE 5 — GASTOS ─────────────────
INSERT IGNORE INTO cuentas_contables (codigo, nombre, tipo, naturaleza, nivel, padre_id, es_movimiento, estado) VALUES
('5',      'GASTOS',                       'GASTO', 'DEBITO', 1, NULL, b'0', 'ACTIVO'),
('51',     'OPERACIONALES DE ADMINISTRACIÓN','GASTO','DEBITO', 2, NULL, b'0', 'ACTIVO'),
('5105',   'GASTOS DE PERSONAL',           'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5110',   'HONORARIOS',                   'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5115',   'IMPUESTOS',                    'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5120',   'ARRENDAMIENTOS',               'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5125',   'CONTRIBUCIONES Y AFILIACIONES','GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5130',   'SEGUROS',                      'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5135',   'SERVICIOS',                    'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5140',   'GASTOS LEGALES',               'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5145',   'MANTENIMIENTO Y REPARACIONES', 'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5150',   'ADECUACIÓN E INSTALACIÓN',     'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5155',   'GASTOS DE VIAJE',              'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5160',   'DEPRECIACIONES',               'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5165',   'AMORTIZACIONES',               'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5195',   'DIVERSOS',                     'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5199',   'PROVISIONES',                  'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),

('52',     'OPERACIONALES DE VENTAS',      'GASTO', 'DEBITO', 2, NULL, b'0', 'ACTIVO'),
('5205',   'GASTOS DE PERSONAL',           'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5210',   'HONORARIOS',                   'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5215',   'IMPUESTOS',                    'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5220',   'ARRENDAMIENTOS',               'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5225',   'CONTRIBUCIONES Y AFILIACIONES','GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5230',   'SEGUROS',                      'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5235',   'SERVICIOS',                    'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5240',   'GASTOS LEGALES',               'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5245',   'MANTENIMIENTO Y REPARACIONES', 'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5250',   'ADECUACIÓN E INSTALACIÓN',     'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5255',   'GASTOS DE VIAJE',              'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5260',   'DEPRECIACIONES',               'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5265',   'AMORTIZACIONES',               'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5295',   'DIVERSOS',                     'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5299',   'PROVISIONES',                  'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),

('53',     'NO OPERACIONALES',             'GASTO', 'DEBITO', 2, NULL, b'0', 'ACTIVO'),
('5305',   'FINANCIEROS',                  'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5310',   'PÉRDIDAS EN VENTA Y RETIRO DE BIENES','GASTO','DEBITO',3,NULL,b'1','ACTIVO'),
('5313',   'PÉRDIDAS MÉTODO DE PARTICIPACIÓN','GASTO','DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5315',   'GASTOS EXTRAORDINARIOS',       'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('5395',   'GASTOS DIVERSOS',              'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),

('54',     'IMPUESTO DE RENTA Y COMPLEMENTARIOS','GASTO','DEBITO',2,NULL, b'1', 'ACTIVO'),
('59',     'GANANCIAS Y PÉRDIDAS',         'GASTO', 'DEBITO', 2, NULL, b'1', 'ACTIVO');

-- ───────────────── CLASE 6 — COSTO DE VENTAS ─────────────────
INSERT IGNORE INTO cuentas_contables (codigo, nombre, tipo, naturaleza, nivel, padre_id, es_movimiento, estado) VALUES
('6',      'COSTOS DE VENTAS',             'GASTO', 'DEBITO', 1, NULL, b'0', 'ACTIVO'),
('61',     'COSTO DE VENTAS Y DE PRESTACIÓN DE SERVICIOS','GASTO','DEBITO',2,NULL,b'0','ACTIVO'),
('6105',   'AGRICULTURA, GANADERÍA, CAZA Y SILVICULTURA','GASTO','DEBITO',3,NULL,b'1','ACTIVO'),
('6135',   'COMERCIO AL POR MAYOR Y AL POR MENOR','GASTO','DEBITO',3,NULL, b'1', 'ACTIVO'),
('6140',   'HOTELES Y RESTAURANTES',       'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('6155',   'ACTIVIDADES INMOBILIARIAS',    'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('62',     'COMPRAS',                      'GASTO', 'DEBITO', 2, NULL, b'0', 'ACTIVO'),
('6205',   'DE MERCANCÍAS',                'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('6210',   'DE MATERIA PRIMA',             'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('6215',   'DE MATERIALES INDIRECTOS',     'GASTO', 'DEBITO', 3, NULL, b'1', 'ACTIVO'),
('6225',   'DEVOLUCIONES EN COMPRAS',      'GASTO', 'CREDITO', 3, NULL, b'1', 'ACTIVO');

-- ───────────────── CLASE 7 — COSTOS DE PRODUCCIÓN ─────────────────
INSERT IGNORE INTO cuentas_contables (codigo, nombre, tipo, naturaleza, nivel, padre_id, es_movimiento, estado) VALUES
('7',      'COSTOS DE PRODUCCIÓN O DE OPERACIÓN','GASTO','DEBITO',1,NULL, b'0', 'ACTIVO'),
('71',     'MATERIA PRIMA',                'GASTO', 'DEBITO', 2, NULL, b'1', 'ACTIVO'),
('72',     'MANO DE OBRA DIRECTA',         'GASTO', 'DEBITO', 2, NULL, b'1', 'ACTIVO'),
('73',     'COSTOS INDIRECTOS',            'GASTO', 'DEBITO', 2, NULL, b'1', 'ACTIVO'),
('74',     'CONTRATOS DE SERVICIOS',       'GASTO', 'DEBITO', 2, NULL, b'1', 'ACTIVO');

-- ═══════════════════════════════════════════════════════════════════════════
-- FIN del PUC oficial Decreto 2650
-- Cuentas auxiliares (nivel 5+) son específicas de cada empresa y se crean
-- desde el CRUD del frontend.
-- ═══════════════════════════════════════════════════════════════════════════
